# run with:
# g3k runjob gentestdata \
# SUBMISSION_HOST submission_host \
# TEST_PROGRAM "" \
# TEST_PROJECT "" \
# NUMBER_OF_EXAMPLES "" \
# NOTE: "" indicates an optional argument. Leave as "" for default
#
# SUBMISSION_HOST(required)
#   url of submission host. e.g. https://giangb.planx-pla.net
#
# TEST_PROJECT(optional)
#   Name of test project. Default: DEV/test
#
# NUMBER_OF_EXAMPLES(optional)
#   Number of examples for each node. Default 1000
#
# Example
# g3k runjob gentestdata SUBMISSION_HOST https://giangb.planx-pla.net TEST_PROGRAM DEV TEST_PROJECT test NUMBER_OF_EXAMPLES 10
apiVersion: batch/v1
kind: Job
metadata:
  name: gentestdata
spec:
  # not yet supported - backOffLimit: 3
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      serviceAccountName: useryaml-job
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: config-volume
          secret:
            secretName: "fence-secret"
        - name: creds-volume
          secret:
            secretName: "fence-creds"
        - name: config-helper
          configMap:
            name: config-helper
        - name: json-secret-volume
          secret:
            secretName: "fence-json-secret"
        - name: fence-jwt-keys
          secret:
            secretName: "fence-jwt-keys"
      containers:
      - name: auto-qa
        image: quay.io/cdis/auto-qa:master
        imagePullPolicy: Always
        env:
          - name: PYTHONPATH
            value: /var/www/fence
          - name: DICTIONARY_URL
            valueFrom:
              configMapKeyRef:
                name: global
                key: dictionary_url
          - name: TEST_PROGRAM
            GEN3_TEST_PROGRAM
          - name: TEST_PROJECT
            GEN3_TEST_PROJECT
          - name: SUBMISSION_HOST
            GEN3_SUBMISSION_HOST
          - name: NUMBER_OF_EXAMPLES
            GEN3_NUMBER_OF_EXAMPLES
        volumeMounts:
          - name: shared-data
            mountPath: /mnt/shared
        command: ["/bin/bash" ]
        args:
          - "-c"
          - |
            let count=0
            while [[ ! -f /mnt/shared/access_token.txt && $count -lt 50 ]]; do
              echo "waiting for /mnt/shared/access_token.txt";
              sleep 2
              let count=$count+1
            done

            mkdir -p /gen3-qa/python-scripts/sim-data-code/TestData

            cd /gen3-qa/python-scripts/sim-data-code/
            rscript_cmd="/gen3-qa/python-scripts/sim-data-code/GenTestDataCmd.R $DICTIONARY_URL"

            if [[ -n "$TEST_PROJECT" ]]; then
                rscript_cmd+=" $TEST_PROJECT"
            else
                rscript_cmd+=" test"
            fi
            if [[ -n "$NUMBER_OF_EXAMPLES" ]]; then
                rscript_cmd+=" $NUMBER_OF_EXAMPLES"
            else
                rscript_cmd+=" 1000"
            fi

            rscript_cmd+=" /gen3-qa/python-scripts/sim-data-code/TestData/"
            echo ${rscript_cmd}
            Rscript ${rscript_cmd}
            python /gen3-qa/python-scripts/scripts.py data-create --host $(SUBMISSION_HOST) --dir /gen3-qa/python-scripts/sim-data-code/TestData/ --project "$TEST_PROGRAM/$TEST_PROJECT" --access_token /mnt/shared/access_token.txt
      - name: fence
        image: quay.io/cdis/fence:master
        imagePullPolicy: Always
        env:
          - name: PYTHONPATH
            value: /var/www/fence
        volumeMounts:
          - name: "config-volume"
            readOnly: true
            mountPath: "/var/www/fence/local_settings.py"
            subPath: local_settings.py
          - name: "creds-volume"
            readOnly: true
            mountPath: "/var/www/fence/creds.json"
            subPath: creds.json
          - name: "config-helper"
            readOnly: true
            mountPath: "/var/www/fence/config_helper.py"
            subPath: config_helper.py
          - name: "json-secret-volume"
            readOnly: true
            mountPath: "/var/www/fence/fence_credentials.json"
            subPath: fence_credentials.json
          - name: "fence-jwt-keys"
            readOnly: true
            mountPath: "/fence/keys"
          - name: shared-data
            mountPath: /mnt/shared
        command: ["/bin/bash" ]
        args:
            - "-c"
            - |
              echo "generate access token"
              fence-create --path fence token-create --type access_token --username cdis.autotest@gmail.com  --scopes openid,user,test-client --exp 3600 > /mnt/shared/access_token.txt
      restartPolicy: Never
