apiVersion: batch/v1
kind: Job
metadata:
  name: update-dict
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      restartPolicy: OnFailure
      serviceAccountName: update-dict-job
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: awshelper
          image: quay.io/cdis/awshelper:master
          imagePullPolicy: Always
          env:
            - name: oldUrl
              valueFrom:
                configMapKeyRef:
                  name: manifest_global
                  key: dictionary_url
            - name: gen3Env
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: environment
          command: ["/bin/bash" ]
          args:
            - "-c"
            - |
              let currentUrl=$(g3k_config_lookup ".global.dictionary_url")
              echo $currentUrl
              echo $oldUrl
              if [[ $currentUrl != $oldUrl ]]; then
                g3kubectl patch configmap manifest_global -p ""
                gen3 kube-roll-all
              fi
              echo "Exit code: $?"