# Note: change to batch/v1beta1 once we bump to k8s 1.8
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-dict
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: gen3job
        spec:
          restartPolicy: Never
          serviceAccountName: useryaml-job
          containers:
            - name: awshelper
              image: quay.io/cdis/awshelper:feat_update-dict
              imagePullPolicy: Always
              env:
                - name: oldUrl
                  valueFrom:
                    configMapKeyRef:
                      name: manifest-global
                      key: dictionary_url
                - name: gen3Env
                  valueFrom:
                    configMapKeyRef:
                      name: global
                      key: environment
              command: ["/bin/bash" ]
              args:
                - "-c"
                - |
                  set -i
                  source ~/.bashrc
                  newUrl=$(g3k_config_lookup ".global.dictionary_url")
                  echo $newUrl
                  echo $oldUrl
                  if [[ $newUrl != $oldUrl ]]; then
                    echo "Dictionary URLs are different updating dictionary"
                    kubectl get pods
                    g3kubectl get pods
                    # g3kubectl patch configmap manifest-global -p '{"data":{"dictionary_url": $newUrl}}'
                    # gen3 kube-roll-all
                  else
                    echo "Dictionary URLs are the same, skipping dictionary update"
                  fi
                  echo "Exit code: $?"
